In [1]:
import pandas as pd

diet_cols = {
    "SEQN": "SEQN",
    "DR1TIRON": "Iron_intake_mg",
    "DR1TTFAT": "Fat_intake_g",
    "DR1TFIBE": "Fiber_intake_g"
}

labs_cols = {
    "SEQN": "SEQN",
    "LBXSIR": "Iron_serum_ug/dL"
}

diet = pd.read_csv("data/NHANES/diet.csv", usecols=lambda c: c in diet_cols.keys()).rename(columns=diet_cols)
labs = pd.read_csv("data/NHANES/labs.csv", usecols=lambda c: c in labs_cols.keys()).rename(columns=labs_cols)

nhanes = diet.merge(labs, on="SEQN", how="left")

fiber_std = nhanes['Fiber_intake_g'].std()
fat_std = nhanes['Fat_intake_g'].std()
iron_intake_std = nhanes['Iron_intake_mg'].std()
    
# For comparison
print(f'Fiber intake std: {fiber_std}')
print(f'Fat intake std: {fat_std}')
print(f'Iron intake std: {iron_intake_std}')

Fiber intake std: 10.132655979964545
Fat intake std: 45.50421029810836
Iron intake std: 8.544092329884053

In [2]:
import numpy as np
import pandas as pd

# Version 1: Links from microbiome -> diet

# Simulate dietary factors based on bacterial abundance
def simulate_dietary_intake(microbiome_sample):
    # Use direct indexing for each bacterium
    bifidobacterium_abundance = microbiome_sample["Bifidobacterium"]
    prevotella_abundance = microbiome_sample["Prevotella"]
    firmicutes_abundance = microbiome_sample["Firmicutes"]
    lactobacillus_abundance = microbiome_sample["Lactobacillus"]
    bacteroides_abundance = microbiome_sample["Bacteroides"]
    proteobacteria_abundance = microbiome_sample["Proteobacteria"]
    
    # Calculate dietary factors using these abundances
    fiber_intake = max(0, (
        15.28 +
        bacteroides_abundance * 25 +
        bifidobacterium_abundance * 15 +
        prevotella_abundance * 10 +
        np.random.normal(0, 10.13)
    ))
    
    fat_intake = max(0, (
        75.10 +
        firmicutes_abundance * 50 +
        lactobacillus_abundance * 5 +
        np.random.normal(0, 15)
    ))
    
    iron_intake = max(0, (
        14.06 +
        bacteroides_abundance * 10 +
        proteobacteria_abundance * 5 + 
        lactobacillus_abundance * 5 +
        np.random.normal(0, 2)
    ))

    return pd.Series({
        'Fiber_intake_g': np.round(fiber_intake, 2),
        'Fat_intake_g': np.round(fat_intake, 2),
        'Iron_intake_mg': np.round(iron_intake, 2)
    })


cleaned_ag_dataset = pd.read_csv('data/combined_ag_data.csv')

# Apply simulation to each microbiome sample
simulated_diet = cleaned_ag_dataset.apply(simulate_dietary_intake, axis=1)
print(simulated_diet.describe())

# Combine simulated diet with microbiome data
combined_data = pd.concat([cleaned_ag_dataset, simulated_diet], axis=1)
combined_data

       Fiber_intake_g  Fat_intake_g  Iron_intake_mg
count     2512.000000   2512.000000     2512.000000
mean        22.099693     97.763487       17.170028
std         11.169837     17.589996        2.738793
min          0.000000     36.040000        8.530000
25%         14.422500     85.997500       15.250000
50%         21.830000     97.465000       17.145000
75%         29.692500    109.540000       19.030000
max         58.890000    160.310000       26.360000

,SampleID,Actinobacteria,Bacteroides,Bacteroidetes,Bifidobacterium,Clostridium,Cyanobacteria,Firmicutes,Fusobacteria,Lactobacillus,Other,Prevotella,Proteobacteria,Tenericutes,Verrucomicrobia,Age,Sex,Fiber_intake_g,Fat_intake_g,Iron_intake_mg
0,000007117.1075649,0.3244,0.0013,0.0315,0.0000,0.0013,0.0352,0.2629,0.0082,0.0027,0.0461,0.0028,0.2821,0.0010,0.0005,59,1,31.76,77.95,16.28
1,000007115.1075661,0.0347,0.0087,0.1735,0.0018,0.0149,0.0289,0.1783,0.0032,0.0166,0.0153,0.0025,0.5196,0.0000,0.0020,59,1,15.70,74.01,19.14
2,000007123.1075697,0.0493,0.0000,0.0153,0.0000,0.0002,0.1265,0.0451,0.0025,0.1222,0.0024,0.0007,0.6347,0.0000,0.0011,59,1,27.07,59.12,18.83
3,000009713.1130401,0.4052,0.0010,0.0091,0.0000,0.0002,0.0265,0.4219,0.0026,0.0015,0.0055,0.0062,0.1191,0.0000,0.0012,70,0,0.00,89.42,16.44
4,000005598.1130569,0.2394,0.0072,0.0401,0.0001,0.0010,0.0255,0.2582,0.0013,0.0170,0.0209,0.0024,0.3828,0.0003,0.0038,72,1,22.43,83.01,12.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2507,000003719.1257129,0.0018,0.0096,0.0028,0.3933,0.0000,0.0001,0.1794,0.0000,0.0016,0.0000,0.0004,0.4108,0.0001,0.0001,57,0,21.21,95.92,14.55
2508,000015353.fixed1024,0.0830,0.0006,0.3497,0.0000,0.0001,0.0000,0.0971,0.0029,0.0000,0.0019,0.0279,0.4360,0.0008,0.0000,35,1,25.34,74.95,18.40
2509,000011980.1210764,0.0050,0.0008,0.0003,0.0000,0.0000,0.0001,0.0023,0.0000,0.9781,0.0000,0.0003,0.0117,0.0014,0.0000,52,0,18.08,81.69,17.71
2510,000005567.1131812,0.0430,0.0006,0.0000,0.0000,0.0000,0.0000,0.0187,0.0003,0.0000,0.0001,0.0012,0.9361,0.0000,0.0000,51,1,22.71,72.26,18.39
2511,000003557.1130030,0.0008,0.0005,0.0005,0.0000,0.0000,0.0000,0.0143,0.0003,0.0000,0.0000,0.0001,0.9835,0.0000,0.0000,46,0,18.05,98.02,19.20

In [3]:
print(cleaned_ag_dataset.describe())

       Actinobacteria  Bacteroides  Bacteroidetes  Bifidobacterium  \
count     2512.000000  2512.000000    2512.000000      2512.000000
mean         0.044008     0.254473       0.071267         0.006304
std          0.105571     0.200699       0.063434         0.019356
min          0.000000     0.000000       0.000000         0.000000
25%          0.001200     0.058150       0.023750         0.000000
50%          0.003100     0.249000       0.058250         0.000500
75%          0.017725     0.403650       0.100475         0.003800
max          0.895200     0.838500       0.615800         0.393300

       Clostridium  Cyanobacteria   Firmicutes  Fusobacteria  Lactobacillus  \
count  2512.000000    2512.000000  2512.000000   2512.000000    2512.000000
mean      0.004090       0.006242     0.446892      0.004176       0.001956
std       0.007518       0.032342     0.196229      0.019339       0.021808
min       0.000000       0.000000     0.000500      0.000000       0.000000
25%       0.000400       0.000000     0.308375      0.000000       0.000000
50%       0.001800       0.000100     0.445100      0.000000       0.000000
75%       0.004600       0.000700     0.576725      0.000300       0.000200
max       0.095500       0.610800     0.988500      0.249600       0.978100

             Other   Prevotella  Proteobacteria  Tenericutes  Verrucomicrobia  \
count  2512.000000  2512.000000     2512.000000  2512.000000      2512.000000
mean      0.001409     0.033701        0.103712     0.005303         0.016467
std       0.005769     0.088367        0.182110     0.014524         0.052503
min       0.000000     0.000000        0.000000     0.000000         0.000000
25%       0.000000     0.000500        0.012075     0.000000         0.000000
50%       0.000100     0.001500        0.028100     0.000100         0.000500
75%       0.000900     0.014025        0.084625     0.003700         0.007725
max       0.124000     0.710900        0.997400     0.200000         0.659900

               Age          Sex
count  2512.000000  2512.000000
mean     47.410430     0.471736
std      14.561941     0.499300
min      18.000000     0.000000
25%      35.000000     0.000000
50%      47.000000     0.000000
75%      59.000000     1.000000
max      93.000000     1.000000

In [4]:
import numpy as np

serum_iron_std = nhanes['Iron_serum_ug/dL'].std()
serum_iron_mean = nhanes['Iron_serum_ug/dL'].mean()

np.random.seed(42)

base = np.random.normal(serum_iron_mean, serum_iron_std * 0.6, len(combined_data))

signal_strength = 1

simulated_iron = (
    base
    + signal_strength * (
        # Dietary factors
        0.3 * combined_data["Iron_intake_mg"]
        + 0.05 * combined_data["Fiber_intake_g"]
        - 0.03 * combined_data["Fat_intake_g"]
        # Microbiome factors
        + 150 * combined_data["Lactobacillus"]
        + 100 * combined_data["Bifidobacterium"]
        + 80 * combined_data["Bacteroides"]
        - 30 * combined_data["Clostridium"]
        # Diet x microbiome
        + 3 * combined_data["Iron_intake_mg"] * combined_data["Lactobacillus"]
        + 1 * combined_data["Fiber_intake_g"] * combined_data["Bifidobacterium"]
        + 0.5 * combined_data["Fat_intake_g"] * combined_data["Lactobacillus"]
        # Diet x diet
        + 0.05 * combined_data["Iron_intake_mg"] * combined_data["Fiber_intake_g"]
        + 0.03 * combined_data["Iron_intake_mg"] * combined_data["Fat_intake_g"]
        # Microbiome x microbiome
        + 200 * combined_data["Lactobacillus"] * combined_data["Bifidobacterium"]
        + 150 * combined_data["Bacteroides"] * combined_data["Lactobacillus"]
        - 250 * combined_data["Firmicutes"] * combined_data["Clostridium"]
    )
    # Demographic factors
    - 0.1 * combined_data["Age"] - 0.001 * combined_data["Age"]**2
    + combined_data["Sex"].map({0: -5, 1: 5}) # females typically have lower iron
    - 60 # offset
)

np.random.seed(123)
interaction_noise = (
    np.random.normal(0, 0.5, len(combined_data)) * combined_data["Iron_intake_mg"] * combined_data["Bifidobacterium"]
    + np.random.normal(0, 0.3, len(combined_data)) * combined_data["Fiber_intake_g"] * combined_data["Clostridium"]
    + np.random.normal(0, 0.2, len(combined_data)) * combined_data["Fat_intake_g"] * combined_data["Bacteroides"]
)

simulated_iron += interaction_noise

# keep within physiological range
simulated_iron = np.clip(simulated_iron, 5, 557)
simulated_iron = np.round(np.array(simulated_iron), 2)

simulated_iron

array([ 98.64,  81.75, 126.16, ..., 283.61,  96.56, 101.23])

In [5]:
# Combine simulated diet with microbiome data
combined_data["Serum_iron_ug"] = simulated_iron

# Drop demographics since we won't use them for predicition
final_data = combined_data.drop(columns=['Age', 'Sex'])

print(final_data["Serum_iron_ug"].describe())
final_data

count    2512.000000
mean      110.494598
std        37.210415
min         5.000000
25%        83.860000
50%       108.585000
75%       134.830000
max       283.610000
Name: Serum_iron_ug, dtype: float64

,SampleID,Actinobacteria,Bacteroides,Bacteroidetes,Bifidobacterium,Clostridium,Cyanobacteria,Firmicutes,Fusobacteria,Lactobacillus,Other,Prevotella,Proteobacteria,Tenericutes,Verrucomicrobia,Fiber_intake_g,Fat_intake_g,Iron_intake_mg,Serum_iron_ug
0,000007117.1075649,0.3244,0.0013,0.0315,0.0000,0.0013,0.0352,0.2629,0.0082,0.0027,0.0461,0.0028,0.2821,0.0010,0.0005,31.76,77.95,16.28,98.64
1,000007115.1075661,0.0347,0.0087,0.1735,0.0018,0.0149,0.0289,0.1783,0.0032,0.0166,0.0153,0.0025,0.5196,0.0000,0.0020,15.70,74.01,19.14,81.75
2,000007123.1075697,0.0493,0.0000,0.0153,0.0000,0.0002,0.1265,0.0451,0.0025,0.1222,0.0024,0.0007,0.6347,0.0000,0.0011,27.07,59.12,18.83,126.16
3,000009713.1130401,0.4052,0.0010,0.0091,0.0000,0.0002,0.0265,0.4219,0.0026,0.0015,0.0055,0.0062,0.1191,0.0000,0.0012,0.00,89.42,16.44,86.55
4,000005598.1130569,0.2394,0.0072,0.0401,0.0001,0.0010,0.0255,0.2582,0.0013,0.0170,0.0209,0.0024,0.3828,0.0003,0.0038,22.43,83.01,12.87,64.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2507,000003719.1257129,0.0018,0.0096,0.0028,0.3933,0.0000,0.0001,0.1794,0.0000,0.0016,0.0000,0.0004,0.4108,0.0001,0.0001,21.21,95.92,14.55,144.43
2508,000015353.fixed1024,0.0830,0.0006,0.3497,0.0000,0.0001,0.0000,0.0971,0.0029,0.0000,0.0019,0.0279,0.4360,0.0008,0.0000,25.34,74.95,18.40,63.49
2509,000011980.1210764,0.0050,0.0008,0.0003,0.0000,0.0000,0.0001,0.0023,0.0000,0.9781,0.0000,0.0003,0.0117,0.0014,0.0000,18.08,81.69,17.71,283.61
2510,000005567.1131812,0.0430,0.0006,0.0000,0.0000,0.0000,0.0000,0.0187,0.0003,0.0000,0.0001,0.0012,0.9361,0.0000,0.0000,22.71,72.26,18.39,96.56
2511,000003557.1130030,0.0008,0.0005,0.0005,0.0000,0.0000,0.0000,0.0143,0.0003,0.0000,0.0000,0.0001,0.9835,0.0000,0.0000,18.05,98.02,19.20,101.23

In [6]:
# Save the data to a CSV
final_data.to_csv("data/final_data.csv", index=False)